# Generated by Django 5.1.2 on 2024-10-23 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_document_remove_apiresponse_document_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='answers',
            field=models.FileField(blank=True, null=True, upload_to='answers/'),
        ),
    ]
