# Generated by Django 5.1.2 on 2024-10-25 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_document_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='previews/'),
        ),
    ]
