# Generated by Django 5.1.2 on 2024-10-28 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_apiresponse_question_id_document_preview_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='apiresponse',
            name='document',
            field=models.ForeignKey(default=75, on_delete=django.db.models.deletion.CASCADE, related_name='api_responses', to='core.document'),
        ),
    ]
